config/routes.rb
Rails.application.routes.draw do
  resources :time_slices
  resources :counters
  post '/counters/:id/api',  to: "counters#update_by_timeSlice"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counter.rb
class Counter < ApplicationRecord
  has_many :time_slices, dependent: :destroy
end

app/models/time_slice.rb
class TimeSlice < ApplicationRecord
  belongs_to :counter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  before_action :set_counter, only: [:show, :edit, :update, :destroy, :update_by_timeSlice]
  skip_before_action  :verify_authenticity_token, only: [:update_by_timeSlice]

  # GET /counters
  # GET /counters.json
  def index
    @counters = Counter.all
  end

  # GET /counters/1
  # GET /counters/1.json
  def show
  end

  # GET /counters/new
  def new
    @counter = Counter.new
  end

  # GET /counters/1/edit
  def edit
  end

  # POST /counters
  # POST /counters.json
  def create
    @counter = Counter.new(counter_params)

    respond_to do |format|
      if @counter.save
        format.html { redirect_to @counter, notice: 'Counter was successfully created.' }
        format.json { render :show, status: :created, location: @counter }
      else
        format.html { render :new }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counters/1
  # PATCH/PUT /counters/1.json
  def update
    respond_to do |format|
      if @counter.update(counter_params)
        format.html { redirect_to @counter, notice: 'Counter was successfully updated.' }
        format.json { render :show, status: :ok, location: @counter }
      else
        format.html { render :edit }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counters/1
  # DELETE /counters/1.json
  def destroy
    @counter.destroy
    respond_to do |format|
      format.html { redirect_to counters_url, notice: 'Counter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_by_timeSlice
    ts = TimeSlice.new(timeSlice_params)
    ts.counter = @counter
    if ts.save() && @counter.update(totalup:(@counter.totalup+ts.up),totaldown:(@counter.totaldown+ts.down))
      return render :json => {'message':'Success'}
    else
      return render :json => {'message':'Fail'}, status: 422
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counter
      @counter = Counter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def counter_params
      params.require(:counter).permit(:totalup, :totaldown)
    end

    def timeSlice_params
      params[:up] = params[:up].to_i
      params[:down] = params[:down].to_i
      params[:created_at] = params[:created_at]
      params.permit(:up,:down,:created_at,:counter_id)
    end
end

app/controllers/time_slices_controller.rb
class TimeSlicesController < ApplicationController
  before_action :set_time_slice, only: [:show, :edit, :update, :destroy]

  # GET /time_slices
  # GET /time_slices.json
  def index
    @time_slices = TimeSlice.all.order('created_at desc')
  end

  # GET /time_slices/1
  # GET /time_slices/1.json
  def show
  end

  # GET /time_slices/new
  def new
    @time_slice = TimeSlice.new
  end

  # GET /time_slices/1/edit
  def edit
  end

  # POST /time_slices
  # POST /time_slices.json
  def create
    @time_slice = TimeSlice.new(time_slice_params)

    respond_to do |format|
      if @time_slice.save
        format.html { redirect_to @time_slice, notice: 'Time slice was successfully created.' }
        format.json { render :show, status: :created, location: @time_slice }
      else
        format.html { render :new }
        format.json { render json: @time_slice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slices/1
  # PATCH/PUT /time_slices/1.json
  def update
    respond_to do |format|
      if @time_slice.update(time_slice_params)
        format.html { redirect_to @time_slice, notice: 'Time slice was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_slice }
      else
        format.html { render :edit }
        format.json { render json: @time_slice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slices/1
  # DELETE /time_slices/1.json
  def destroy
    @time_slice.destroy
    respond_to do |format|
      format.html { redirect_to time_slices_url, notice: 'Time slice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slice
      @time_slice = TimeSlice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_slice_params
      params.require(:time_slice).permit(:up, :down, :counter_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_datetime(datetime)
    datetime.strftime('%Y/%m/%d %H:%M:%S')
  end
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/helpers/time_slices_helper.rb
module TimeSlicesHelper
end

app/views/counters/_form.html.erb
<%= form_with(model: counter, local: true) do |form| %>
  <% if counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
        <% counter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :totalup %>
    <%= form.number_field :totalup %>
  </div>

  <div class="field">
    <%= form.label :totaldown %>
    <%= form.number_field :totaldown %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/counters/edit.html.erb
<h1>Editing Counter</h1>

<%= render 'form', counter: @counter %>

<%= link_to 'Show', @counter %> |
<%= link_to 'Back', counters_path %>

app/views/counters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Counters</h1>

<table>
  <thead>
    <tr>
      <th>Totalup</th>
      <th>Totaldown</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counters.each do |counter| %>
      <tr>
        <td><%= counter.totalup %></td>
        <td><%= counter.totaldown %></td>
        <td><%= link_to 'Show', counter %></td>
        <td><%= link_to 'Edit', edit_counter_path(counter) %></td>
        <td><%= link_to 'Destroy', counter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Counter', new_counter_path %>

app/views/counters/new.html.erb
<h1>New Counter</h1>

<%= render 'form', counter: @counter %>

<%= link_to 'Back', counters_path %>

app/views/counters/show.html.erb
<% content_for :head do %>
  <meta http-equiv="refresh" content="5; URL=<%= counters_path %>">
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Totalup:</strong>
  <%= @counter.totalup %>
</p>

<p>
  <strong>Totaldown:</strong>
  <%= @counter.totaldown %>
</p>

<%= link_to 'Edit', edit_counter_path(@counter) %> |
<%= link_to 'Back', counters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleCounter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%=yield :head %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/time_slices/_form.html.erb
<%= form_with(model: time_slice, local: true) do |form| %>
  <% if time_slice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_slice.errors.count, "error") %> prohibited this time_slice from being saved:</h2>

      <ul>
        <% time_slice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :up %>
    <%= form.number_field :up %>
  </div>

  <div class="field">
    <%= form.label :down %>
    <%= form.number_field :down %>
  </div>

  <div class="field">
    <%= form.label :counter_id %>
    <%= form.number_field :counter_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_slices/edit.html.erb
<h1>Editing Time Slice</h1>

<%= render 'form', time_slice: @time_slice %>

<%= link_to 'Show', @time_slice %> |
<%= link_to 'Back', time_slices_path %>

app/views/time_slices/index.html.erb
<% content_for :head do %>
  <meta http-equiv="refresh" content="5; URL=<%= time_slices_path %>">
<% end %>

<p id="notice"><%= notice %></p>

<h1>Time Slices</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Up</th>
      <th>Down</th>
      <th>Created_at</th>
      <th>Updated_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_slices.each do |time_slice| %>
      <tr>
        <td><%= time_slice.id %></td>
        <td><%= time_slice.up %></td>
        <td><%= time_slice.down %></td>
        <td><%= format_datetime time_slice.created_at %></td>
        <td><%= format_datetime time_slice.updated_at %></td>
        <td><%= link_to 'Show', time_slice %></td>
        <td><%= link_to 'Edit', edit_time_slice_path(time_slice) %></td>
        <td><%= link_to 'Destroy', time_slice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Slice', new_time_slice_path %>

app/views/time_slices/new.html.erb
<h1>New Time Slice</h1>

<%= render 'form', time_slice: @time_slice %>

<%= link_to 'Back', time_slices_path %>

app/views/time_slices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Up:</strong>
  <%= @time_slice.up %>
</p>

<p>
  <strong>Down:</strong>
  <%= @time_slice.down %>
</p><p>
  <strong>Created_at:</strong>
  <%= @time_slice.created_at %>
</p><p>
  <strong>Updated_at:</strong>
  <%= @time_slice.updated_at %>
</p>

<%= link_to 'Edit', edit_time_slice_path(@time_slice) %> |
<%= link_to 'Back', time_slices_path %>